from enum import Enum

NO_BASE_NAME = 'NO_BASE_NAME'

ALIGN_ANGLE_THRESHOLD = 0.001


class SpriteType(Enum):
	DEFAULT = 'DEFAULT'
	SELECTED = 'SELECTED'
	HIGHLIGHTED = 'HIGHLIGHTED'
	CLICKED = 'CLICKED'
